# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

language: android
jdk: oraclejdk8

# Use the Travis Container-Based Infrastructure
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  global:
    - ANDROID_API_LEVEL=27
    - ANDROID_BUILD_TOOLS=27.0.3

    # there is no arm build for 27, and versions after 23 have a strange problem
    # we test on 22 anyways as it doesn't have java 8, and we'd like to catch bugs on older apis
    - EMULATOR_API_LEVEL=22

    - ADB_INSTALL_TIMEOUT=8 # minutes

android:
  components:
    # this section is required for versions 24 and up (tools is required twice)
    # https://docs.travis-ci.com/user/languages/android/#Installing-a-newer-SDK-Platform-Tools-revision
    - tools
    - platform-tools
    - tools

    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL

    # downloads all extra components
    - extra

    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

before_script:
  # List all preinstalled targets. This helps when debugging the raw log
  - android list targets

  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a --tag google_apis
  - export QEMU_AUDIO_DRV=none && emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
